config/routes.rb
DsgnrsIn::Application.routes.draw do
  constraints(:host => "www.dsgnrs.in") do
    # Won't match root path without brackets around "*x". (using Rails 3.0.3)
    get "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "dsgnrs.in" }.to_s
    }
  end

  get "/feed", :to => 'syndicator#feed'

  resources :users
  # will give routes for users:
  # index, new, create, show, edit, update, destroy

  get "sessions/create"
  get "sessions/destroy"

  get "/auth/failure" => "sessions#failure"
  get "/auth/twitter/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "/sitemap", :to => 'sitemap#index', :as => :sitemap

  get "/apply" => "users#edit", :as => :apply
  get "/profile" => "users#edit", :as => :profile

  get "/curate/:status", :to => 'curate#index', :as => :curate
  get "/:city", :to => 'cities#index', :as => :city

  root :to => "users#index"
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{'http-equiv' => 'X-UA-Compatible',
          :content => 'IE=edge,chrome=1'}
    - users_count = 0
    - users_count = @users.length if @users
    - if @city
      %title Designer#{ users_count == 1 ? "" : "s"} in #{@city.name}
    - else
      %title Designer#{ users_count == 1 ? "" : "s"} in India

    = yield :meta_desicription
    %meta{:name => "viewport",
          :content => "width=device-width"}
    %meta{:name => "apple-mobile-web-app-capable",
          :content => "yes"}

    = stylesheet_link_tag 'application', :media => 'all'
    %link{:rel=> "logo",
          :type=> "image/svg",
          :href=> asset_path('logo.svg')}
    %link{:href => "https://fonts.googleapis.com/css?family=Source+Serif+Pro:400,600",
          :rel => "stylesheet"}


    = csrf_meta_tags
  %body{:class => @body_classnames }
    - if flash[:success]
      .notification.success
        .wrapper
          .notificaion-inner
            %p= flash[:success]
            %a.dismiss{:href => "#"} ×
    - if flash[:notice]
      .notification
        .wrapper
          .notificaion-inner
            %p= flash[:notice]
            %a.dismiss{:href => "#"} ×
    - if flash[:error]
      .notification.error
        .wrapper
          .notificaion-inner
            %p= flash[:error]
            %a.dismiss{:href => "#"} ×
    #mobile-menu-wrapper
    %header.wrapper.header
      .d1
        %h1
          %span.site-title Designer#{ users_count == 1 ? "" : "s"} in
          %span.change-city.dropdown
            %a#city-menu-trigger{:href =>"#",
               :title => "Change City",
               "data-toggle" => "dropdown"}<
              = @city ? @city.name : "India"
              %span.icon-location>
            %ul#city-menu.dropdown-menu{:role => "menu",
                              "aria-labelledby" => "Cities"}
              - cities_with_users.each do |city|
                %li
                  %a{:href => "/#{city.slug}"}= city.name
              %li.divider
              %li
                %a{:href => "/"} India
      .d2.minor
        %p.tagline= site_tagline

    .wrapper
      = yield

      .d2
        .sidebar
          - if current_user && (not current_user.is_approved.nil?)
            = link_to "Profile", profile_path, :class => "button", :title => "Your Profile"
          - else
            = link_to "Apply", apply_path, :class => "button", :title => "Apply To Get Listed"

    %footer
      .wrapper
        .d1.footer-major
          %p
            - if current_user
              %a.button{ :href => signout_path, :title => "Sign Out" }< Sign Out
            - else
              %a.button{ :href => "/auth/twitter", :title => "Sign In with Twitter" }<
                %span.icon-twitter
                Sign In
            &nbsp;
            %span Follow
            %a{ :href => "http://twitter.com/dsgnrs_in",
              :title => "dsgnrs.in on Twitter" } @dsgnrs_in
            %span.m-hide to get updates

          %p.minor.m-hide <a href="//github.com/saneef/dsgnrs.in" title="dsgnrs.in Source on Github">Github</a> · This project is inspired [or counterfeited ;-)] from the <a href="http://n-y-p-d.com/"><abbr title="New York Product Designers">NYPD</abbr></a>.
        .d2.footer-minor
          %a{ :href => root_path,
              :title => 'Designers of India',
              :class => 'logo' }
            %span.icon-logo
          %p.minor Made by <a href="http://saneef.com">Saneef</a>.

    = javascript_include_tag 'application'

    - if on_production?
      %script
        :plain
          var _gaq=[['_setAccount','#{ENV['GA_TRACKING_ID']}'],['_trackPageview']];
          (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
          s.parentNode.insertBefore(g,s)}(document,'script'));